<a href="https://colab.research.google.com/github/prajjaldhar/DataScience/blob/main/Pandas_Full_Notes_and_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas — Full Notes + Practice Notebook

Pandas notebook covering Series, DataFrames, indexing, `loc`, `iloc`, fancy indexing, boolean indexing, inspection, cleaning, transformations, `groupby`, `merge`, `join`, `concat`, dates and file I/O.

## 1. What is Pandas?

**Pandas** is a Python library for data manipulation and analysis.

Its two fundamental structures are:

- **Series** → one-dimensional labeled data
- **DataFrame** → two-dimensional labeled/tabular data

Typical data-analysis workflow:

**Load → Inspect → Clean → Transform → Analyze → Export**

In [ ]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)

Pandas: 2.2.3

## 2. Series

A Series stores values together with an index. The index can be numeric, textual, dates, or another label.

### Series creation — Example 1

In [ ]:
pd.Series([10, 20, 30, 40])

0    10
1    20
2    30
3    40
dtype: int64

### Series creation — Example 2

In [ ]:
pd.Series(["Python", "Java", "C++"], index=["a", "b", "c"])

a    Python
b      Java
c       C++
dtype: object

### Series creation — Example 3

In [ ]:
pd.Series({"Delhi": 190, "Mumbai": 125, "Bhopal": 18})

Delhi     190
Mumbai    125
Bhopal     18
dtype: int64

### Series creation — Example 4

In [ ]:
pd.Series(100, index=["Mon", "Tue", "Wed", "Thu"])

Mon    100
Tue    100
Wed    100
Thu    100
dtype: int64

### Series creation — Example 5

In [ ]:
pd.Series(np.arange(5, 15, 2))

0     5
1     7
2     9
3    11
4    13
dtype: int64

### Series creation — Example 6

In [ ]:
pd.Series([True, False, True], name="attendance")

0     True
1    False
2     True
Name: attendance, dtype: bool

### Series creation — Example 7

In [ ]:
pd.Series([4.5, 3.2, 5.0], index=["Math", "Physics", "DSA"], name="CGPA")

Math       4.5
Physics    3.2
DSA        5.0
Name: CGPA, dtype: float64

### Series creation — Example 8

In [ ]:
pd.Series(["A", "B", "A", "C"], dtype="category")

0    A
1    B
2    A
3    C
dtype: category
Categories (3, object): ['A', 'B', 'C']

### Series creation — Example 9

In [ ]:
pd.Series(pd.date_range("2026-01-01", periods=5), name="dates")

0   2026-01-01
1   2026-01-02
2   2026-01-03
3   2026-01-04
4   2026-01-05
Name: dates, dtype: datetime64[ns]

### Series creation — Example 10

In [ ]:
pd.Series([100, None, 250, None, 400], name="sales")

0    100.0
1      NaN
2    250.0
3      NaN
4    400.0
Name: sales, dtype: float64

In [ ]:
dates = pd.date_range("2026-01-01", periods=5)
sales = pd.Series([100, None, 250, None, 400], index=dates, name="sales")
print(sales)
print(sales.isnull())
print(sales.isnull().sum())
print(sales.notnull())
print(sales.notnull().sum())
print(sales.hasnans)
print(sales.count())
print(sales.fillna(0))
print(sales.dropna())

2026-01-01    100.0
2026-01-02      NaN
2026-01-03    250.0
2026-01-04      NaN
2026-01-05    400.0
Freq: D, Name: sales, dtype: float64
2026-01-01    False
2026-01-02     True
2026-01-03    False
2026-01-04     True
2026-01-05    False
Freq: D, Name: sales, dtype: bool
2
2026-01-01     True
2026-01-02    False
2026-01-03     True
2026-01-04    False
2026-01-05     True
Freq: D, Name: sales, dtype: bool
3
True
3
2026-01-01    100.0
2026-01-02      0.0
2026-01-03    250.0
2026-01-04      0.0
2026-01-05    400.0
Freq: D, Name: sales, dtype: float64
2026-01-01    100.0
2026-01-03    250.0
2026-01-05    400.0
Name: sales, dtype: float64

## 3. Series Attributes

Important attributes: `index`, `values`, `dtype`, `shape`, `size`, `ndim`, `name`, `empty`, `hasnans`. `unique()` and `nunique()` are methods.

In [ ]:
sales = pd.Series([1200, 850, 910, 1500,850],
                  index=["Mon", "Tue", "Wed", "Thu","Fri"],
                  name="daily_sales")

print("index:", sales.index)
print("values:", sales.values)
print("dtype:", sales.dtype)
print("shape:", sales.shape)
print("size:", sales.size)
print("ndim:", sales.ndim)
print("name:", sales.name)
print("empty:", sales.empty)
print("hasnans:", sales.hasnans)
print("unique:", sales.unique())
print("is unique:", sales.is_unique)
print("nunique:", sales.nunique())

index: Index(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], dtype='object')
values: [1200  850  910 1500  850]
dtype: int64
shape: (5,)
size: 5
ndim: 1
name: daily_sales
empty: False
hasnans: False
unique: [1200  850  910 1500]
is unique: False
nunique: 4

## 4. Series Indexing — 10 Different Scenarios

### Indexing scenario 1

In [ ]:
pd.Series([78,91,66,88], index=["Aman","Riya","Kabir","Neha"])["Riya"]

np.int64(91)

### Indexing scenario 2

In [ ]:
pd.Series([120,80,250], index=["Pen","Notebook","Bag"])["Notebook"]

np.int64(80)

### Indexing scenario 3

In [ ]:
pd.Series([31,33,29,35,32])[2]

np.int64(29)

### Indexing scenario 4

In [ ]:
pd.Series([45,78,91,66,88])[1:4]

1    78
2    91
3    66
dtype: int64

### Indexing scenario 5

In [ ]:
pd.Series([11,22,33], index=["Jaipur","Bhopal","Indore"])[["Indore","Jaipur"]]

Indore    33
Jaipur    11
dtype: int64

### Indexing scenario 6

In [ ]:
pd.Series([100,105,98,110], index=["Mon","Tue","Wed","Thu"])[lambda s: s > 100]

Tue    105
Thu    110
dtype: int64

### Indexing scenario 7

In [ ]:
pd.Series([52000,68000,45000], index=["Dev","QA","HR"]).loc["QA"]

np.int64(68000)

### Indexing scenario 8

In [ ]:
pd.Series(["Python","Java","C++"], index=[101,102,103]).loc[102]

'Java'

### Indexing scenario 9

In [ ]:
pd.Series([10,20,30,40,50]).iloc[[0,2,4]]

0    10
2    30
4    50
dtype: int64

### Indexing scenario 10

In [ ]:
pd.Series([92,76,88,61], index=["A","B","C","D"]).loc[["A","C"]]

A    92
C    88
dtype: int64

## 5. `loc` vs `iloc`

`loc` is label-based. `iloc` is position-based. `loc` label slices are generally inclusive; `iloc` follows Python's exclusive stop rule.

### `loc` / `iloc` example 1

In [ ]:
pd.Series([10,20,30,40], index=["a","b","c","d"]).loc["b"]

np.int64(20)

### `loc` / `iloc` example 2

In [ ]:
pd.Series([10,20,30,40], index=["a","b","c","d"]).loc["b":"d"]

b    20
c    30
d    40
dtype: int64

### `loc` / `iloc` example 3

In [ ]:
pd.Series([10,20,30,40]).iloc[2]

np.int64(30)

### `loc` / `iloc` example 4

In [ ]:
pd.Series([10,20,30,40]).iloc[1:3]

1    20
2    30
dtype: int64

### `loc` / `iloc` example 5

In [ ]:
pd.Series([10,20,30,40], index=["w","x","y","z"]).loc[["w","z"]]

w    10
z    40
dtype: int64

### `loc` / `iloc` example 6

In [ ]:
pd.Series([10,20,30,40]).iloc[[0,3]]

0    10
3    40
dtype: int64

### `loc` / `iloc` example 7

In [ ]:
pd.Series([50,20,80,40], index=["A","B","C","D"]).loc[lambda s: s > 45]

A    50
C    80
dtype: int64

### `loc` / `iloc` example 8

In [ ]:
pd.Series([50,20,80,40]).iloc[np.array([True,False,True,False])]

0    50
2    80
dtype: int64

### `loc` / `iloc` example 9

In [ ]:
pd.Series([100,200,300], index=["x","y","z"]).loc.__class__

pandas.core.indexing._LocIndexer

### `loc` / `iloc` example 10

In [ ]:
pd.Series([100,200,300], index=["x","y","z"]).iloc.__class__

pandas.core.indexing._iLocIndexer

## 6. Series Methods — 10 Scenarios

### Method scenario 1

In [ ]:
pd.Series([4,1,7,2,7]).agg(["sum","mean","median","min","max"])

sum       21.0
mean       4.2
median     4.0
min        1.0
max        7.0
dtype: float64

### Method scenario 2

In [ ]:
pd.Series(["python","java","python","cpp"]).value_counts()

python    2
java      1
cpp       1
Name: count, dtype: int64

### Method scenario 3

In [ ]:
pd.Series([10,None,30,None,50]).fillna(0)

0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64

### Method scenario 4

In [ ]:
pd.Series([5,2,9,1]).sort_values(ascending=False)

2    9
0    5
1    2
3    1
dtype: int64

### Method scenario 5

In [ ]:
pd.Series([100,200,300], index=["c","a","b"]).sort_index()

a    200
b    300
c    100
dtype: int64

### Method scenario 6

In [ ]:
pd.Series(["  Delhi","Mumbai  ","  Pune  "]).str.strip()

0     Delhi
1    Mumbai
2      Pune
dtype: object

### Method scenario 7

In [ ]:
pd.Series(["python","java","c++"]).str.upper()

0    PYTHON
1      JAVA
2       C++
dtype: object

### Method scenario 8

In [ ]:
pd.Series([10,20,30]).add(5).multiply(2)

0    30
1    50
2    70
dtype: int64

### Method scenario 9

In [ ]:
pd.Series([1,2,3,4,5]).cumsum()

0     1
1     3
2     6
3    10
4    15
dtype: int64

### Method scenario 10

In [ ]:
pd.Series([1,2,3,4,5]).describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

### Series method reference

Common Series methods:

`head()`, `tail()`, `describe()`, `sum()`, `mean()`, `median()`, `mode()`, `min()`, `max()`, `std()`, `var()`, `count()`, `nunique()`, `unique()`, `value_counts()`, `sort_values()`, `sort_index()`, `rank()`, `cumsum()`, `cumprod()`, `cummin()`, `cummax()`, `diff()`, `shift()`, `fillna()`, `dropna()`, `isna()`, `notna()`, `astype()`, `clip()`, `round()`, `replace()`, `where()`, `mask()`, `between()`, `isin()`, `map()`, `apply()`.

For text data, use the `.str` accessor: `upper`, `lower`, `strip`, `len`, `contains`, `startswith`, `endswith`, `split`, `replace`, etc.

## 7. DataFrames

A DataFrame is a two-dimensional labeled table. Each column behaves like a Series sharing the same row index.

In [ ]:
students = pd.DataFrame({
    "name": ["Aman", "Riya", "Kabir", "Neha"],
    "age": [20, 21, 19, 22],
    "marks": [82, 91, 74, 88],
    "city": ["Bhopal", "Indore", "Jaipur", "Bhopal"]
})
students

    name  age  marks    city
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### DataFrame creation — Example 1

In [ ]:
pd.DataFrame({"x":[1,2,3], "y":[4,5,6]})

   x  y
0  1  4
1  2  5
2  3  6

### DataFrame creation — Example 2

In [ ]:
pd.DataFrame([["A",20],["B",21]], columns=["name","age"])

  name  age
0    A   20
1    B   21

### DataFrame creation — Example 3

In [ ]:
pd.DataFrame({"product":["Mouse","Keyboard"],"price":[799,1499]}, index=["P1","P2"])

     product  price
P1     Mouse    799
P2  Keyboard   1499

### DataFrame creation — Example 4

In [ ]:
pd.DataFrame(np.arange(12).reshape(3,4), columns=["A","B","C","D"])

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

### DataFrame creation — Example 5

In [ ]:
pd.DataFrame({"city":["Delhi","Pune"],"population_m":[32,7]})

    city  population_m
0  Delhi            32
1   Pune             7

### DataFrame creation — Example 6

In [ ]:
pd.DataFrame.from_dict({"Java":[80,90],"Python":[95,88]})

   Java  Python
0    80      95
1    90      88

### DataFrame creation — Example 7

In [ ]:
pd.DataFrame({"date":pd.date_range("2026-01-01",periods=3),"sales":[100,150,120]})

        date  sales
0 2026-01-01    100
1 2026-01-02    150
2 2026-01-03    120

### DataFrame creation — Example 8

In [ ]:
pd.DataFrame([{"id":1,"score":88},{"id":2,"score":91}])

   id  score
0   1     88
1   2     91

### DataFrame creation — Example 9

In [ ]:
pd.DataFrame({"active":[True,False,True],"users":[100,0,250]})

   active  users
0    True    100
1   False      0
2    True    250

### DataFrame creation — Example 10

In [ ]:
pd.DataFrame(np.random.randint(1,100,size=(4,3)), columns=["Math","DSA","Python"])

   Math  DSA  Python
0    53   84      70
1    64   89      60
2    35   82      50
3    18   63      11

## 8. DataFrame Attributes

In [ ]:
print("shape:", students.shape)
print("columns:", students.columns)
print("index:", students.index)
print("dtypes:\n", students.dtypes)
print("size:", students.size)
print("ndim:", students.ndim)
print("empty:", students.empty)
print("values:\n", students.values)

shape: (4, 4)
columns: Index(['name', 'age', 'marks', 'city'], dtype='object')
index: RangeIndex(start=0, stop=4, step=1)
dtypes:
 name     object
age       int64
marks     int64
city     object
dtype: object
size: 16
ndim: 2
empty: False
values:
 [['Aman' 20 82 'Bhopal']
 ['Riya' 21 91 'Indore']
 ['Kabir' 19 74 'Jaipur']
 ['Neha' 22 88 'Bhopal']]

## 9. `head()`, `tail()`, `describe()`, `info()` — 10 Scenarios

### Inspection scenario 1

In [ ]:
students.head()

    name  age  marks    city
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Inspection scenario 2

In [ ]:
students.head(2)

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore

### Inspection scenario 3

In [ ]:
students.tail()

    name  age  marks    city
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Inspection scenario 4

In [ ]:
students.tail(2)

    name  age  marks    city
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Inspection scenario 5

In [ ]:
students.describe()

             age  marks
count   4.000000   4.00
mean   20.500000  83.75
std     1.290994   7.50
min    19.000000  74.00
25%    19.750000  80.00
50%    20.500000  85.00
75%    21.250000  88.75
max    22.000000  91.00

### Inspection scenario 6

In [ ]:
students.describe(include="all")

        name        age  marks    city
count      4   4.000000   4.00       4
unique     4        NaN    NaN       3
top     Aman        NaN    NaN  Bhopal
freq       1        NaN    NaN       2
mean     NaN  20.500000  83.75     NaN
std      NaN   1.290994   7.50     NaN
min      NaN  19.000000  74.00     NaN
25%      NaN  19.750000  80.00     NaN
50%      NaN  20.500000  85.00     NaN
75%      NaN  21.250000  88.75     NaN
max      NaN  22.000000  91.00     NaN

### Inspection scenario 7

In [ ]:
students[["age","marks"]].describe()

             age  marks
count   4.000000   4.00
mean   20.500000  83.75
std     1.290994   7.50
min    19.000000  74.00
25%    19.750000  80.00
50%    20.500000  85.00
75%    21.250000  88.75
max    22.000000  91.00

### Inspection scenario 8

In [ ]:
students["marks"].describe()

count     4.00
mean     83.75
std       7.50
min      74.00
25%      80.00
50%      85.00
75%      88.75
max      91.00
Name: marks, dtype: float64

### Inspection scenario 9

In [ ]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   marks   4 non-null      int64
 3   city    4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

### Inspection scenario 10

In [ ]:
students.sample(2, random_state=42)

   name  age  marks    city
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

## 10. Column Selection / Column Names — 10 Scenarios

### Column scenario 1

In [ ]:
students["name"]

0     Aman
1     Riya
2    Kabir
3     Neha
Name: name, dtype: object

### Column scenario 2

In [ ]:
students[["name","city"]]

    name    city
0   Aman  Bhopal
1   Riya  Indore
2  Kabir  Jaipur
3   Neha  Bhopal

### Column scenario 3

In [ ]:
students.loc[:, "marks"]

0    82
1    91
2    74
3    88
Name: marks, dtype: int64

### Column scenario 4

In [ ]:
students.loc[:, ["age","marks"]]

   age  marks
0   20     82
1   21     91
2   19     74
3   22     88

### Column scenario 5

In [ ]:
students.iloc[:, 0]

0     Aman
1     Riya
2    Kabir
3     Neha
Name: name, dtype: object

### Column scenario 6

In [ ]:
students.iloc[:, [0,2]]

    name  marks
0   Aman     82
1   Riya     91
2  Kabir     74
3   Neha     88

### Column scenario 7

In [ ]:
students[students.columns[1]]

0    20
1    21
2    19
3    22
Name: age, dtype: int64

### Column scenario 8

In [ ]:
students.filter(items=["name","marks"])

    name  marks
0   Aman     82
1   Riya     91
2  Kabir     74
3   Neha     88

### Column scenario 9

In [ ]:
students.filter(like="a", axis="columns")

    name  age  marks
0   Aman   20     82
1   Riya   21     91
2  Kabir   19     74
3   Neha   22     88

### Column scenario 10

In [ ]:
students.columns.tolist()

['name', 'age', 'marks', 'city']

## 11. Row Selection — 10 Scenarios

### Row-selection scenario 1

In [ ]:
students.loc[0]

name       Aman
age          20
marks        82
city     Bhopal
Name: 0, dtype: object

### Row-selection scenario 2

In [ ]:
students.loc[1:3]

    name  age  marks    city
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Row-selection scenario 3

In [ ]:
students.iloc[0]

name       Aman
age          20
marks        82
city     Bhopal
Name: 0, dtype: object

### Row-selection scenario 4

In [ ]:
students.iloc[1:3]

    name  age  marks    city
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur

### Row-selection scenario 5

In [ ]:
students.loc[[0,2]]

    name  age  marks    city
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur

### Row-selection scenario 6

In [ ]:
students.iloc[[0,3]]

   name  age  marks    city
0  Aman   20     82  Bhopal
3  Neha   22     88  Bhopal

### Row-selection scenario 7

In [ ]:
students.loc[students["marks"] > 80]

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

### Row-selection scenario 8

In [ ]:
students.iloc[:2, :]

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore

### Row-selection scenario 9

In [ ]:
students.loc[:, "name":"marks"]

    name  age  marks
0   Aman   20     82
1   Riya   21     91
2  Kabir   19     74
3   Neha   22     88

### Row-selection scenario 10

In [ ]:
students.iloc[:, 1:3]

   age  marks
0   20     82
1   21     91
2   19     74
3   22     88

## 12. Fancy Indexing — 10 Scenarios

### Fancy-indexing example 1

In [ ]:
students.loc[[0,2,3]]

    name  age  marks    city
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Fancy-indexing example 2

In [ ]:
students.iloc[[3,0,1]]

   name  age  marks    city
3  Neha   22     88  Bhopal
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore

### Fancy-indexing example 3

In [ ]:
students.loc[[0,3], ["name","marks"]]

   name  marks
0  Aman     82
3  Neha     88

### Fancy-indexing example 4

In [ ]:
students.iloc[[0,2], [1,2]]

   age  marks
0   20     82
2   19     74

### Fancy-indexing example 5

In [ ]:
students.loc[students["city"].isin(["Bhopal","Jaipur"]), ["name","city"]]

    name    city
0   Aman  Bhopal
2  Kabir  Jaipur
3   Neha  Bhopal

### Fancy-indexing example 6

In [ ]:
students.loc[[True,False,True,False]]

    name  age  marks    city
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur

### Fancy-indexing example 7

In [ ]:
students.iloc[[True,False,False,True]]

   name  age  marks    city
0  Aman   20     82  Bhopal
3  Neha   22     88  Bhopal

### Fancy-indexing example 8

In [ ]:
students.loc[:, ["marks","name"]]

   marks   name
0     82   Aman
1     91   Riya
2     74  Kabir
3     88   Neha

### Fancy-indexing example 9

In [ ]:
students.iloc[:, [2,0]]

   marks   name
0     82   Aman
1     91   Riya
2     74  Kabir
3     88   Neha

### Fancy-indexing example 10

In [ ]:
students.loc[students["marks"].nlargest(2).index, ["name","marks"]]

   name  marks
1  Riya     91
3  Neha     88

## 13. Boolean Indexing — 10 Scenarios

### Boolean scenario 1

In [ ]:
students[students["marks"] > 80]

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

### Boolean scenario 2

In [ ]:
students[students["age"] >= 21]

   name  age  marks    city
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

### Boolean scenario 3

In [ ]:
students[(students["marks"] > 80) & (students["age"] < 22)]

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore

### Boolean scenario 4

In [ ]:
students[(students["city"] == "Bhopal") | (students["marks"] > 85)]

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

### Boolean scenario 5

In [ ]:
students[~(students["city"] == "Bhopal")]

    name  age  marks    city
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur

### Boolean scenario 6

In [ ]:
students[students["city"].isin(["Bhopal","Jaipur"])]

    name  age  marks    city
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Boolean scenario 7

In [ ]:
students[students["marks"].between(75,90)]

   name  age  marks    city
0  Aman   20     82  Bhopal
3  Neha   22     88  Bhopal

### Boolean scenario 8

In [ ]:
students[students["name"].str.startswith("A")]

   name  age  marks    city
0  Aman   20     82  Bhopal

### Boolean scenario 9

In [ ]:
students[students["name"].str.contains("e", case=False)]

   name  age  marks    city
3  Neha   22     88  Bhopal

### Boolean scenario 10

In [ ]:
students.query("marks >= 80 and age < 22")

   name  age  marks    city
0  Aman   20     82  Bhopal
1  Riya   21     91  Indore

## 14. Adding, Updating, Renaming and Dropping Columns

In [ ]:
df = students.copy()
df["passed"] = df["marks"] >= 40
df["bonus"] = df["marks"] + 5
df.loc[df["name"] == "Kabir", "marks"] = 79
df = df.rename(columns={"marks":"score"})
df = df.drop(columns=["bonus"])
df

    name  age  score    city  passed
0   Aman   20     82  Bhopal    True
1   Riya   21     91  Indore    True
2  Kabir   19     79  Jaipur    True
3   Neha   22     88  Bhopal    True

## 15. Missing Values — 10 Scenarios

### Missing-value scenario 1

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[None,5,6]}).isna()

       A      B
0  False   True
1   True  False
2  False  False

### Missing-value scenario 2

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[None,5,6]}).isna().sum()

A    1
B    1
dtype: int64

### Missing-value scenario 3

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[None,5,6]}).dropna()

     A    B
2  3.0  6.0

### Missing-value scenario 4

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[None,5,6]}).dropna(axis="columns")

Empty DataFrame
Columns: []
Index: [0, 1, 2]

### Missing-value scenario 5

In [ ]:
pd.DataFrame({"A":[1,None,3]}).fillna(0)

     A
0  1.0
1  0.0
2  3.0

### Missing-value scenario 6

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[None,5,6]}).fillna({"A":100,"B":200})

       A      B
0    1.0  200.0
1  100.0    5.0
2    3.0    6.0

### Missing-value scenario 7

In [ ]:
pd.Series([10,None,30]).fillna(pd.Series([10,None,30]).mean())

0    10.0
1    20.0
2    30.0
dtype: float64

### Missing-value scenario 8

In [ ]:
pd.DataFrame({"A":[1,None,None,4]}).ffill()

     A
0  1.0
1  1.0
2  1.0
3  4.0

### Missing-value scenario 9

In [ ]:
pd.DataFrame({"A":[1,None,None,4]}).bfill()

     A
0  1.0
1  4.0
2  4.0
3  4.0

### Missing-value scenario 10

In [ ]:
pd.DataFrame({"A":[1,None,3],"B":[4,5,6]}).dropna(subset=["A"])

     A  B
0  1.0  4
2  3.0  6

## 16. Sorting — 10 Scenarios

### Sorting scenario 1

In [ ]:
students.sort_values("marks")

    name  age  marks    city
2  Kabir   19     74  Jaipur
0   Aman   20     82  Bhopal
3   Neha   22     88  Bhopal
1   Riya   21     91  Indore

### Sorting scenario 2

In [ ]:
students.sort_values("marks", ascending=False)

    name  age  marks    city
1   Riya   21     91  Indore
3   Neha   22     88  Bhopal
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur

### Sorting scenario 3

In [ ]:
students.sort_values(["city","marks"])

    name  age  marks    city
0   Aman   20     82  Bhopal
3   Neha   22     88  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur

### Sorting scenario 4

In [ ]:
students.sort_values(["city","marks"], ascending=[True,False])

    name  age  marks    city
3   Neha   22     88  Bhopal
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur

### Sorting scenario 5

In [ ]:
students.sort_index(ascending=False)

    name  age  marks    city
3   Neha   22     88  Bhopal
2  Kabir   19     74  Jaipur
1   Riya   21     91  Indore
0   Aman   20     82  Bhopal

### Sorting scenario 6

In [ ]:
students.nlargest(2,"marks")

   name  age  marks    city
1  Riya   21     91  Indore
3  Neha   22     88  Bhopal

### Sorting scenario 7

In [ ]:
students.nsmallest(2,"age")

    name  age  marks    city
2  Kabir   19     74  Jaipur
0   Aman   20     82  Bhopal

### Sorting scenario 8

In [ ]:
students.assign(rank=students["marks"].rank(ascending=False))

    name  age  marks    city  rank
0   Aman   20     82  Bhopal   3.0
1   Riya   21     91  Indore   1.0
2  Kabir   19     74  Jaipur   4.0
3   Neha   22     88  Bhopal   2.0

### Sorting scenario 9

In [ ]:
students.sort_values("name", key=lambda s:s.str.lower())

    name  age  marks    city
0   Aman   20     82  Bhopal
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal
1   Riya   21     91  Indore

### Sorting scenario 10

In [ ]:
students.sort_values("marks").reset_index(drop=True)

    name  age  marks    city
0  Kabir   19     74  Jaipur
1   Aman   20     82  Bhopal
2   Neha   22     88  Bhopal
3   Riya   21     91  Indore

## 17. `apply`, `map`, `replace`, `astype` — 10 Scenarios

### Transformation scenario 1

In [ ]:
students["marks"].apply(lambda x:x+2)

0    84
1    93
2    76
3    90
Name: marks, dtype: int64

### Transformation scenario 2

In [ ]:
students["name"].map(lambda x:x.upper())

0     AMAN
1     RIYA
2    KABIR
3     NEHA
Name: name, dtype: object

### Transformation scenario 3

In [ ]:
students["city"].replace({"Bhopal":"BPL","Indore":"IND"})

0       BPL
1       IND
2    Jaipur
3       BPL
Name: city, dtype: object

### Transformation scenario 4

In [ ]:
students["age"].astype(float)

0    20.0
1    21.0
2    19.0
3    22.0
Name: age, dtype: float64

### Transformation scenario 5

In [ ]:
students["marks"].clip(lower=0, upper=90)

0    82
1    90
2    74
3    88
Name: marks, dtype: int64

### Transformation scenario 6

In [ ]:
students["name"].str.lower()

0     aman
1     riya
2    kabir
3     neha
Name: name, dtype: object

### Transformation scenario 7

In [ ]:
students["name"].str.len()

0    4
1    4
2    5
3    4
Name: name, dtype: int64

### Transformation scenario 8

In [ ]:
students["city"].str.contains("pur", case=False)

0    False
1    False
2     True
3    False
Name: city, dtype: bool

### Transformation scenario 9

In [ ]:
students.assign(double_marks=students["marks"]*2)

    name  age  marks    city  double_marks
0   Aman   20     82  Bhopal           164
1   Riya   21     91  Indore           182
2  Kabir   19     74  Jaipur           148
3   Neha   22     88  Bhopal           176

### Transformation scenario 10

In [ ]:
students.assign(result=students["marks"].apply(lambda x:"Pass" if x>=40 else "Fail"))

    name  age  marks    city result
0   Aman   20     82  Bhopal   Pass
1   Riya   21     91  Indore   Pass
2  Kabir   19     74  Jaipur   Pass
3   Neha   22     88  Bhopal   Pass

## 18. GroupBy

In [ ]:
sales = pd.DataFrame({
    "city":["Bhopal","Bhopal","Indore","Indore","Jaipur","Jaipur"],
    "category":["Laptop","Phone","Laptop","Phone","Laptop","Phone"],
    "sales":[80000,45000,92000,50000,78000,42000],
    "units":[4,9,5,10,4,8]
})
sales

     city category  sales  units
0  Bhopal   Laptop  80000      4
1  Bhopal    Phone  45000      9
2  Indore   Laptop  92000      5
3  Indore    Phone  50000     10
4  Jaipur   Laptop  78000      4
5  Jaipur    Phone  42000      8

### GroupBy scenario 1

In [ ]:
sales.groupby("city")["sales"].sum()

city
Bhopal    125000
Indore    142000
Jaipur    120000
Name: sales, dtype: int64

### GroupBy scenario 2

In [ ]:
sales.groupby("city")["sales"].mean()

city
Bhopal    62500.0
Indore    71000.0
Jaipur    60000.0
Name: sales, dtype: float64

### GroupBy scenario 3

In [ ]:
sales.groupby("category")["units"].sum()

category
Laptop    13
Phone     27
Name: units, dtype: int64

### GroupBy scenario 4

In [ ]:
sales.groupby(["city","category"])["sales"].sum()

city    category
Bhopal  Laptop      80000
        Phone       45000
Indore  Laptop      92000
        Phone       50000
Jaipur  Laptop      78000
        Phone       42000
Name: sales, dtype: int64

### GroupBy scenario 5

In [ ]:
sales.groupby("city").agg({"sales":"sum","units":"mean"})

         sales  units
city
Bhopal  125000    6.5
Indore  142000    7.5
Jaipur  120000    6.0

### GroupBy scenario 6

In [ ]:
sales.groupby("city")["sales"].agg(["sum","mean","max"])

           sum     mean    max
city
Bhopal  125000  62500.0  80000
Indore  142000  71000.0  92000
Jaipur  120000  60000.0  78000

### GroupBy scenario 7

In [ ]:
sales.groupby("city").size()

city
Bhopal    2
Indore    2
Jaipur    2
dtype: int64

### GroupBy scenario 8

In [ ]:
sales.groupby("city")["sales"].transform("mean")

0    62500.0
1    62500.0
2    71000.0
3    71000.0
4    60000.0
5    60000.0
Name: sales, dtype: float64

### GroupBy scenario 9

In [ ]:
sales.groupby("city").filter(lambda g:g["sales"].sum()>100000)

     city category  sales  units
0  Bhopal   Laptop  80000      4
1  Bhopal    Phone  45000      9
2  Indore   Laptop  92000      5
3  Indore    Phone  50000     10
4  Jaipur   Laptop  78000      4
5  Jaipur    Phone  42000      8

### GroupBy scenario 10

In [ ]:
sales.groupby("city", as_index=False)["sales"].sum()

     city   sales
0  Bhopal  125000
1  Indore  142000
2  Jaipur  120000

## 19. Merge

In [ ]:
customers = pd.DataFrame({
    "customer_id":[1,2,3],
    "name":["Aman","Riya","Kabir"]
})
orders = pd.DataFrame({
    "customer_id":[1,1,2,4],
    "amount":[500,800,1200,700]
})

### Merge scenario 1

In [ ]:
pd.merge(customers, orders, on="customer_id")

   customer_id  name  amount
0            1  Aman     500
1            1  Aman     800
2            2  Riya    1200

### Merge scenario 2

In [ ]:
pd.merge(customers, orders, on="customer_id", how="left")

   customer_id   name  amount
0            1   Aman   500.0
1            1   Aman   800.0
2            2   Riya  1200.0
3            3  Kabir     NaN

### Merge scenario 3

In [ ]:
pd.merge(customers, orders, on="customer_id", how="right")

   customer_id  name  amount
0            1  Aman     500
1            1  Aman     800
2            2  Riya    1200
3            4   NaN     700

### Merge scenario 4

In [ ]:
pd.merge(customers, orders, on="customer_id", how="outer")

   customer_id   name  amount
0            1   Aman   500.0
1            1   Aman   800.0
2            2   Riya  1200.0
3            3  Kabir     NaN
4            4    NaN   700.0

### Merge scenario 5

In [ ]:
pd.merge(customers, orders, on="customer_id", how="inner")

   customer_id  name  amount
0            1  Aman     500
1            1  Aman     800
2            2  Riya    1200

### Merge scenario 6

In [ ]:
pd.merge(customers, orders, left_on="customer_id", right_on="customer_id")

   customer_id  name  amount
0            1  Aman     500
1            1  Aman     800
2            2  Riya    1200

### Merge scenario 7

In [ ]:
pd.merge(pd.DataFrame({"id":[1,2],"value":[10,20]}), pd.DataFrame({"id":[1,2],"value":[100,200]}), on="id", suffixes=("_left","_right"))

   id  value_left  value_right
0   1          10          100
1   2          20          200

### Merge scenario 8

In [ ]:
customers.set_index("customer_id").join(orders.set_index("customer_id"), how="left")

              name  amount
customer_id
1             Aman   500.0
1             Aman   800.0
2             Riya  1200.0
3            Kabir     NaN

### Merge scenario 9

In [ ]:
pd.merge(customers, orders, on="customer_id", indicator=True, how="outer")

   customer_id   name  amount      _merge
0            1   Aman   500.0        both
1            1   Aman   800.0        both
2            2   Riya  1200.0        both
3            3  Kabir     NaN   left_only
4            4    NaN   700.0  right_only

### Merge scenario 10

In [ ]:
pd.merge(customers, orders, on="customer_id", validate="one_to_many")

   customer_id  name  amount
0            1  Aman     500
1            1  Aman     800
2            2  Riya    1200

## 20. `concat()` and `join()` — 10 Scenarios

### Concat/Join scenario 1

In [ ]:
pd.concat([students.iloc[:2], students.iloc[2:]])

    name  age  marks    city
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal

### Concat/Join scenario 2

In [ ]:
pd.concat([students, students], ignore_index=True)

    name  age  marks    city
0   Aman   20     82  Bhopal
1   Riya   21     91  Indore
2  Kabir   19     74  Jaipur
3   Neha   22     88  Bhopal
4   Aman   20     82  Bhopal
5   Riya   21     91  Indore
6  Kabir   19     74  Jaipur
7   Neha   22     88  Bhopal

### Concat/Join scenario 3

In [ ]:
pd.concat([students[["name"]], students[["marks"]]], axis=1)

    name  marks
0   Aman     82
1   Riya     91
2  Kabir     74
3   Neha     88

### Concat/Join scenario 4

In [ ]:
pd.concat([pd.Series([1,2]), pd.Series([3,4])], ignore_index=True)

0    1
1    2
2    3
3    4
dtype: int64

### Concat/Join scenario 5

In [ ]:
pd.concat([pd.DataFrame({"A":[1,2]}), pd.DataFrame({"B":[3,4]})], axis=1)

   A  B
0  1  3
1  2  4

### Concat/Join scenario 6

In [ ]:
pd.DataFrame({"score":[80,90]}, index=["A","B"]).join(pd.DataFrame({"grade":["B","A"]}, index=["A","B"]))

   score grade
A     80     B
B     90     A

### Concat/Join scenario 7

In [ ]:
pd.DataFrame({"score":[80,90]}, index=["A","B"]).join(pd.DataFrame({"grade":["B","A"]}, index=["A","B"]), how="outer")

   score grade
A     80     B
B     90     A

### Concat/Join scenario 8

In [ ]:
pd.DataFrame({"score":[80,90]}, index=["A","B"]).join(pd.DataFrame({"score":[81,91]}, index=["A","B"]), lsuffix="_old", rsuffix="_new")

   score_old  score_new
A         80         81
B         90         91

### Concat/Join scenario 9

In [ ]:
pd.concat([students,students], axis=0, keys=["batch1","batch2"])

           name  age  marks    city
batch1 0   Aman   20     82  Bhopal
       1   Riya   21     91  Indore
       2  Kabir   19     74  Jaipur
       3   Neha   22     88  Bhopal
batch2 0   Aman   20     82  Bhopal
       1   Riya   21     91  Indore
       2  Kabir   19     74  Jaipur
       3   Neha   22     88  Bhopal

### Concat/Join scenario 10

In [ ]:
pd.concat([students,students], axis=1, keys=["copy1","copy2"])

   copy1                    copy2
    name age marks    city   name age marks    city
0   Aman  20    82  Bhopal   Aman  20    82  Bhopal
1   Riya  21    91  Indore   Riya  21    91  Indore
2  Kabir  19    74  Jaipur  Kabir  19    74  Jaipur
3   Neha  22    88  Bhopal   Neha  22    88  Bhopal

## 21. Duplicates — 10 Scenarios

### Duplicate scenario 1

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3],"name":["A","B","B","C"]}); d.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

### Duplicate scenario 2

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3],"name":["A","B","B","C"]}); d.drop_duplicates()

   id name
0   1    A
1   2    B
3   3    C

### Duplicate scenario 3

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3],"name":["A","B","B","C"]}); d.drop_duplicates(subset=["id"])

   id name
0   1    A
1   2    B
3   3    C

### Duplicate scenario 4

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3],"name":["A","B","B","C"]}); d.drop_duplicates(subset=["id"], keep="last")

   id name
0   1    A
2   2    B
3   3    C

### Duplicate scenario 5

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3]}); d.duplicated("id").sum()

np.int64(1)

### Duplicate scenario 6

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3]}); d[d.duplicated("id", keep=False)]

   id
1   2
2   2

### Duplicate scenario 7

In [ ]:
d = pd.Series([1,2,2,3]); d.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

### Duplicate scenario 8

In [ ]:
d = pd.Series([1,2,2,3]); d.drop_duplicates()

0    1
1    2
3    3
dtype: int64

### Duplicate scenario 9

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3]}); d.drop_duplicates(ignore_index=True)

   id
0   1
1   2
2   3

### Duplicate scenario 10

In [ ]:
d = pd.DataFrame({"id":[1,2,2,3]}); d.assign(is_duplicate=d.duplicated("id", keep=False))

   id  is_duplicate
0   1         False
1   2          True
2   2          True
3   3         False

## 22. DateTime — 10 Scenarios

### DateTime scenario 1

In [ ]:
pd.to_datetime(["2026-01-01","2026-02-15"])

DatetimeIndex(['2026-01-01', '2026-02-15'], dtype='datetime64[ns]', freq=None)

### DateTime scenario 2

In [ ]:
pd.to_datetime(["2026-01-01","2026-06-15"]).year

Index([2026, 2026], dtype='int32')

### DateTime scenario 3

In [ ]:
pd.to_datetime(["2026-01-01","2026-06-15"]).month

Index([1, 6], dtype='int32')

### DateTime scenario 4

In [ ]:
pd.to_datetime(["2026-01-01","2026-06-15"]).day

Index([1, 15], dtype='int32')

### DateTime scenario 5

In [ ]:
pd.to_datetime(["2026-01-01","2026-06-15"]).day_name()

Index(['Thursday', 'Monday'], dtype='object')

### DateTime scenario 6

In [ ]:
dfd = pd.DataFrame({"date":pd.date_range("2026-01-01", periods=5)}); dfd["month"]=dfd["date"].dt.month; dfd

        date  month
0 2026-01-01      1
1 2026-01-02      1
2 2026-01-03      1
3 2026-01-04      1
4 2026-01-05      1

### DateTime scenario 7

In [ ]:
dfd["weekday"]=dfd["date"].dt.day_name(); dfd

        date  month   weekday
0 2026-01-01      1  Thursday
1 2026-01-02      1    Friday
2 2026-01-03      1  Saturday
3 2026-01-04      1    Sunday
4 2026-01-05      1    Monday

### DateTime scenario 8

In [ ]:
dfd["quarter"]=dfd["date"].dt.quarter; dfd

        date  month   weekday  quarter
0 2026-01-01      1  Thursday        1
1 2026-01-02      1    Friday        1
2 2026-01-03      1  Saturday        1
3 2026-01-04      1    Sunday        1
4 2026-01-05      1    Monday        1

### DateTime scenario 9

In [ ]:
dfd["date_plus_7"]=dfd["date"]+pd.Timedelta(days=7); dfd

        date  month   weekday  quarter date_plus_7
0 2026-01-01      1  Thursday        1  2026-01-08
1 2026-01-02      1    Friday        1  2026-01-09
2 2026-01-03      1  Saturday        1  2026-01-10
3 2026-01-04      1    Sunday        1  2026-01-11
4 2026-01-05      1    Monday        1  2026-01-12

### DateTime scenario 10

In [ ]:
dfd[dfd["date"]>="2026-01-03"]

        date  month   weekday  quarter date_plus_7
2 2026-01-03      1  Saturday        1  2026-01-10
3 2026-01-04      1    Sunday        1  2026-01-11
4 2026-01-05      1    Monday        1  2026-01-12

## 23. File I/O

Common functions:

- `pd.read_csv()` / `df.to_csv()`
- `pd.read_excel()` / `df.to_excel()`
- `pd.read_json()` / `df.to_json()`
- `pd.read_sql()` for SQL databases

Always inspect loaded data using `head()`, `shape`, `columns`, `dtypes`, `info()` and `describe()`.

In [ ]:
# Uncomment when files exist:
# df = pd.read_csv("sales.csv")
# df = pd.read_excel("sales.xlsx")
# df.to_csv("clean_sales.csv", index=False)
# df.to_excel("clean_sales.xlsx", index=False)

## 24. Useful Advanced Selection Patterns

In [ ]:
students.select_dtypes(include="number")
students.filter(regex="name|city")
students.query("marks >= 80")
students.sample(n=2, random_state=1)
students.T

            0       1       2       3
name     Aman    Riya   Kabir    Neha
age        20      21      19      22
marks      82      91      74      88
city   Bhopal  Indore  Jaipur  Bhopal

## 25. Pandas Cheat Sheet

| Task | Syntax |
|---|---|
| One column | `df["col"]` |
| Multiple columns | `df[["a","b"]]` |
| Label selection | `df.loc[...]` |
| Position selection | `df.iloc[...]` |
| First rows | `df.head()` |
| Last rows | `df.tail()` |
| Summary | `df.describe()` |
| Sort | `df.sort_values()` |
| Missing | `df.isna()` |
| Remove missing | `df.dropna()` |
| Fill missing | `df.fillna()` |
| Group | `df.groupby()` |
| Merge | `pd.merge()` |
| Stack | `pd.concat()` |
| Duplicates | `df.drop_duplicates()` |
| Boolean filter | `df[df["x"] > 10]` |
| Query filter | `df.query("x > 10")` |

## 26. Practice Questions — 20 From Each Major Topic

### Series Creation & Basics

1. Create a Series of eight monthly expenses with month names as the index.

2. Create a Series from a dictionary of five cities and populations.

3. Create a constant Series of 50 for seven days.

4. Create a Series using np.arange from 10 to 50 with step 5.

5. Create a boolean Series named is_present.

6. Create a Series with non-consecutive numeric indexes.

7. Create a Series containing five dates.

8. Create a Series of product names with product IDs as labels.

9. Create a Series with an explicit float dtype.

10. Create a named Series called CGPA.

11. Print its index.

12. Print only its values.

13. Print dtype, shape, size and ndim.

14. Check whether it is empty.

15. Check whether it contains NaN.

16. Find unique values.

17. Find number of unique values.

18. Count frequencies with value_counts().

19. Create a categorical Series.

20. Explain why Series is one-dimensional and labeled.

### Series Indexing / loc / iloc

1. Select one value by label.

2. Select one value by position.

3. Select three labels with loc.

4. Select positions 0, 2 and 4 with iloc.

5. Slice labels from B through E.

6. Slice positions 1 through 3.

7. Update a value using loc.

8. Update a value using iloc.

9. Select values above a threshold.

10. Select two named labels in custom order.

11. Use a boolean mask with loc.

12. Use a boolean positional mask with iloc.

13. Use a Series with labels 101, 205, 309 and demonstrate loc vs iloc.

14. Select the last two positions.

15. Select every second position.

16. Reverse a Series with positional slicing.

17. Select labels in a non-sorted order.

18. Insert/update a new label using loc.

19. Select a label range and explain inclusivity.

20. Write a short example showing why integer labels can make loc and iloc confusing.

### Series Methods

1. Calculate sum, mean and median.

2. Find min and max temperature.

3. Calculate standard deviation and variance.

4. Generate descriptive statistics.

5. Find the mode.

6. Sort values ascending.

7. Sort values descending.

8. Sort the index.

9. Calculate cumulative sum.

10. Calculate cumulative product.

11. Calculate day-to-day diff.

12. Compare current and previous values with shift.

13. Fill NaN with zero.

14. Fill NaN with the mean.

15. Drop NaN.

16. Replace selected values.

17. Use clip to cap extremes.

18. Use between to select a numeric interval.

19. Use isin to select selected categories.

20. Use map/apply to transform values.

### DataFrame Creation / Attributes / Inspection

1. Create a DataFrame from a dictionary of lists.

2. Create one from a list of dictionaries.

3. Create one from a NumPy matrix.

4. Create one with a custom index.

5. Create one containing dates.

6. Print shape and size.

7. Print ndim.

8. Print columns and index.

9. Print dtypes.

10. Show first three rows.

11. Show last two rows.

12. Run describe().

13. Run describe(include='all').

14. Show random rows.

15. Run info().

16. Select numeric columns by dtype.

17. Select string columns by dtype.

18. Rename two columns.

19. Set and reset an index.

20. Explain shape versus size.

### DataFrame Indexing / Columns / Fancy Indexing

1. Select one column.

2. Select multiple columns.

3. Select rows by labels.

4. Select rows by positions.

5. Select rows 0 and 4.

6. Select two rows and two columns.

7. Reorder columns with a list.

8. Reorder rows with a list.

9. Select every second row.

10. Select every second column.

11. Use fancy indexing for custom row order.

12. Select rows using a list of labels and columns using a list.

13. Select top two scores using nlargest.

14. Select categories with isin.

15. Select a rectangular label-based block.

16. Select a rectangular positional block.

17. Update one cell with loc.

18. Update several matching rows.

19. Show a case where loc and iloc return different data.

20. Explain why df[['a']] is a DataFrame but df['a'] is a Series.

### Boolean Indexing / query

1. Filter employees earning above 60000.

2. Filter students younger than 21.

3. Filter products between two prices.

4. Filter two cities.

5. Exclude one city.

6. Combine two conditions with &.

7. Combine two conditions with |.

8. Negate a condition with ~.

9. Use isin with three values.

10. Use between().

11. Filter strings starting with A.

12. Filter strings containing 'an'.

13. Filter case-insensitively.

14. Use query() for one condition.

15. Use query() for two AND conditions.

16. Use query() with OR.

17. Use a Python variable inside query().

18. Filter non-null scores.

19. Store a boolean mask in a variable.

20. Use a mask to return only selected columns.

### GroupBy / Aggregation

1. Total sales by city.

2. Average sales by city.

3. Maximum transaction by category.

4. Order count by customer.

5. Total units by product.

6. Group by city and category.

7. Calculate sum, mean and max together.

8. Use agg with different functions for different columns.

9. Use as_index=False.

10. Count rows using size().

11. Find the city with highest total sales.

12. Filter groups using a group-level condition.

13. Calculate each employee's percentage of department total.

14. Use transform to add a group mean.

15. Median score by class.

16. Standard deviation by branch.

17. Monthly revenue using date grouping.

18. Group by three categorical dimensions.

19. Sort grouped results by an aggregate.

20. Explain split-apply-combine using your own example.

### Merge / Join / Concat

1. Perform an inner merge on customer_id.

2. Perform a left merge.

3. Perform a right merge.

4. Perform an outer merge.

5. Merge tables with differently named key columns.

6. Handle duplicate non-key column names with suffixes.

7. Use indicator=True.

8. Validate a one-to-many relationship.

9. Join two DataFrames by index.

10. Perform an outer join by index.

11. Concatenate two tables vertically.

12. Concatenate vertically with ignore_index=True.

13. Concatenate two tables horizontally.

14. Concatenate Series objects.

15. Concatenate with keys.

16. Combine tables with non-overlapping columns.

17. Explain inner versus left join.

18. Find records only in the left table.

19. Find unmatched records using merge indicator.

20. Explain when concat is preferable to merge.

### Missing Values / Cleaning

1. Detect missing values.

2. Count missing values per column.

3. Calculate missing-value percentages.

4. Drop rows containing NaN.

5. Drop columns containing NaN.

6. Fill all NaN with zero.

7. Fill columns with different constants.

8. Fill numeric NaN with the column mean.

9. Forward-fill a time series.

10. Backward-fill a time series.

11. Drop rows only when one specific column is missing.

12. Convert -1 placeholders to NaN.

13. Convert empty strings to NaN.

14. Check whether a Series has any NaN.

15. Create a non-null count report.

16. Compare dropna and fillna.

17. Fill categorical NaN with mode.

18. Fill missing values using group means.

19. Verify that no NaN remains.

20. Explain why blindly filling every NaN with zero can be wrong.

### Sorting / Transformation / Duplicates

1. Sort salaries ascending.

2. Sort prices descending.

3. Sort by two columns in different directions.

4. Sort the index descending.

5. Find three largest records.

6. Find two smallest records.

7. Rank students by marks.

8. Apply a custom numeric function.

9. Map department codes to names.

10. Replace multiple categories.

11. Convert a numeric column to float.

12. Cap extreme values using clip.

13. Create a derived revenue column.

14. Create pass/fail using apply.

15. Find duplicate rows.

16. Remove duplicate rows.

17. Remove duplicates based on one key.

18. Keep the last duplicate.

19. Display every duplicated record.

20. Explain duplicated() versus drop_duplicates().

### DateTime / File I/O

1. Convert a date column to datetime.

2. Extract year.

3. Extract month.

4. Extract weekday name.

5. Filter rows after a date.

6. Create a 30-day date range.

7. Add seven days to dates.

8. Calculate the difference between two dates.

9. Group revenue by month.

10. Group revenue by quarter.

11. Read a CSV.

12. Read only selected CSV columns.

13. Use a CSV column as the index.

14. Export a cleaned DataFrame to CSV.

15. Read an Excel sheet.

16. Export to Excel.

17. Read JSON.

18. Write JSON.

19. Inspect dtypes immediately after loading.

20. Build a load-inspect-clean-export pipeline.

## 27. Mini Project — E-commerce Analysis

Create an e-commerce DataFrame with at least 50 rows and:

`order_id, customer_id, city, category, product, quantity, price, discount, order_date, payment_method`

Perform:

1. Inspection
2. Missing-value analysis
3. Duplicate detection
4. Revenue calculation
5. Boolean filtering
6. Top products
7. City-wise sales
8. Category-wise sales
9. Monthly sales
10. Customer-wise totals
11. Merge customer information
12. Export the cleaned dataset